### ISSUE TITLE
Duplicate keys in attack parameter dictionaries

### ISSUE THREAD

**Issue by johannesjung** [lsgos/uncertainty-adversarial-paper#1] opened 2018-05-12 15:19 UTC
Hi,

some of the attack parameter dictionaries contain the key `"eps_iter"` two times. The dictionaries with

-  `"method": "bim"`, `"eps": 5` and
-  `"method": "mim"`, `"eps": 5` do so.

Cheers,
Johannes

https://github.com/lsgos/uncertainty-adversarial-paper/blob/559af3e4a5df7727db3ec6c3493831c81618887c/ROC_curves_cats.py#L359-L394

**Comment by lsgos** [comment] 2018-05-12 16:37
Hi,
This is indeed a mistake (the second key will override the first) ; however, its luckily not too serious, as 0.5 is an ok setting of the eps_iter parameter here
I don't think I'm going to change this, as this repository is intended to allow the exact reproduction of the experiments in the paper draft, including any mistakes, so changing it would defeat that purpose.
However, thanks for raising it; I have some other code that is based on this that suffered from the same bug, which I have now fixed

**Closed as completed** 2018-05-14 21:33 UTC
